export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const CHARACTERS_GET_REQUEST = "CHARACTERS_GET_REQUEST";
export const CHARACTERS_GET_SUCCESS = "CHARACTERS_GET_SUCCESS";
export const CHARACTERS_GET_FAILURE = "CHARACTERS_GET_FAILURE";

export const SAVE_EVENT_REQUEST = "SAVE_EVENT_REQUEST";
export const SAVE_EVENT_SUCCESS = "SAVE_EVENT_SUCCESS";

export const HISTORY_GET_REQUEST = "HISTORY_GET_REQUEST";
export const HISTORY_GET_SUCCESS = "HISTORY_GET_SUCCESS";
export const HISTORY_GET_FAILURE = "HISTORY_GET_FAILURE";